<a href="https://colab.research.google.com/github/ashukrji/First-Repo/blob/master/Exp1_ML_LAB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## ARRAYS IN NUMPY

In [22]:
import numpy as np

# CREATE A NUMPY ARRAY

In [23]:
a=np.array([1,2,3])
b=np.array([[1,2,3],[4,5,6]])

print(a.ndim)
print(b.ndim)



1
2


# Accessing the array index

In [24]:
print(a[2])
print(b[1][1])

3
5


# Perform basic addition (adding 1 to every element) and subtraction (subtracting 2 from each element) operation.


In [27]:

print(a+1)
print(a-2)

[2 3 4]
[-1  0  1]


## Data Types in Numpy

In [28]:
a.dtype

dtype('int64')

In [34]:
b.dtype


dtype('float32')

# construct a datatype object

In [37]:
print(np.dtype(np.float64))

float64


## different Methods in Numpy (Implement 10 methods)

## *np.zeros*()

In [40]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# np.ones()

In [41]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## range()

In [51]:

l=range(5)
l
for x in l:
  print(x)


0
1
2
3
4


## np.arange()

In [53]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [54]:
np.arange(1,8,2)

array([1, 3, 5, 7])

# np.Linspace()

In [55]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [56]:
np.linspace(1,4,7)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

# reshape()

In [63]:
b.shape


(2, 6)

In [65]:
b.reshape(12,1)


array([[1.e-45],
       [0.e+00],
       [3.e-45],
       [0.e+00],
       [4.e-45],
       [0.e+00],
       [6.e-45],
       [0.e+00],
       [7.e-45],
       [0.e+00],
       [8.e-45],
       [0.e+00]], dtype=float32)

## ravel()

In [71]:
c=np.array([[1,2,3,4],
            [12,23,45,56],
            [34,56,78,80]]
           )
c.ravel()

array([ 1,  2,  3,  4, 12, 23, 45, 56, 34, 56, 78, 80])

## min()

In [73]:
c.min()

1

## max()

In [74]:
c.max()

80

## sum()

In [76]:
c.sum()

394

In [77]:
c.sum(axis=0) #column wise sum

array([ 47,  81, 126, 140])

In [80]:
c.sum(axis=1) # row wise sum

array([ 10, 136, 248])

## unique elements in the array using numpy.

In [83]:
d=np.array([1,1,2,3,44,4,4,5,6,7,7,7,9])
np.unique(d)

array([ 1,  2,  3,  4,  5,  6,  7,  9, 44])